# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# The assistant project unique identifier
# This default value must be replaced with a unique assistant name within your deployment
assistant_id: 20250429-182457-commutative-paint

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en
version: "3.1"



pipeline:
  - name: WhitespaceTokenizer
  - name: CountVectorsFeaturizer
  - name: DIETClassifier
    epochs: 100
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 50
  - name: FallbackClassifier
    threshold: 0.3

policies:
  - name: MemoizationPolicy
    max_history: 5
  - name: RulePolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 100
